services:
  backend:
    build:
      context: .
      dockerfile: src/apps/ecommerce/backend/Dockerfile
      target: production
    environment:
      PORT: 3000
    ports:
      - '3000:3000'
    healthcheck:
      test: wget --no-verbose --tries=1 --spider backend:3000
      interval: 3s
      timeout: 3s
      retries: 30
      start_period: 0s
    restart: on-failure

  frontend:
    build:
      context: src/apps/ecommerce/frontend
      dockerfile: Dockerfile
      target: production
      args:
        BACKEND_URL: 'http://localhost:3000/v1'
    environment:
      PORT: 3030
    ports:
      - '3030:3030'
    depends_on:
      backend:
        condition: service_healthy
        restart: true
