services:
  backend-test:
    build:
      context: src/apps/ecommerce/backend
      dockerfile: Dockerfile.dev
    environment:
      NODE_ENV: test
      PORT: 3000
    ports:
      - '3000:3000'
    volumes:
      - .:/app
    healthcheck:
      test: wget --no-verbose --tries=1 --spider backend-test:3000
      interval: 3s
      timeout: 3s
      retries: 30
      start_period: 0s
    restart: on-failure

  frontend-test:
    build:
      context: src/apps/ecommerce/frontend
      dockerfile: Dockerfile.dev
    environment:
      PORT: 3030
      VITE_BACKEND_URL: 'http://backend-test:3000/v1'
    ports:
      - '3030:3030'
    volumes:
      - .:/app
    depends_on:
      backend-test:
        condition: service_healthy
        restart: true
    healthcheck:
      test: wget --no-verbose --tries=1 --spider frontend-test:3030
      interval: 3s
      timeout: 3s
      retries: 30
      start_period: 0s

  tests:
    build:
      context: tests
      dockerfile: Dockerfile.dev
    environment:
      BACKEND_URL: 'http://backend-test:3000'
      FRONTEND_URL: 'http://frontend-test:3030'
      PLAYWRIGHT_CHROMIUM_EXECUTABLE_PATH: '/usr/bin/chromium-browser'
    volumes:
      - .:/app
    depends_on:
      frontend-test:
        condition: service_healthy
        restart: true
