services:
  backend-dev:
    build:
      context: src/apps/ecommerce/backend
      dockerfile: Dockerfile.dev
    environment:
      NODE_ENV: development
      PORT: 1000
    ports:
      - '1000:1000'
    volumes:
      - .:/app
    healthcheck:
      test: wget --no-verbose --tries=1 --spider backend-dev:1000
      interval: 3s
      timeout: 3s
      retries: 30
      start_period: 0s
    restart: on-failure

  frontend-dev:
    build:
      context: src/apps/ecommerce/frontend
      dockerfile: Dockerfile.dev
    environment:
      PORT: 1010
      VITE_BACKEND_URL: 'http://localhost:1000/v1'
    ports:
      - '1010:1010'
    volumes:
      - .:/app
    depends_on:
      backend-dev:
        condition: service_healthy
        restart: true
