services:
  backend-dev:
    build:
      context: src/apps/ecommerce/backend
      dockerfile: Dockerfile.dev
    environment:
      NODE_ENV: development
      HOST: backend-dev
      PORT: 5172
      FRONTEND_HOST: frontend-dev
      FRONTEND_PORT: 5173
    ports:
      - '5172:5172'
    volumes:
      - .:/app
    healthcheck:
      test: wget --no-verbose --tries=1 --spider backend-dev:5172
      interval: 3s
      timeout: 3s
      retries: 30
      start_period: 0s

  frontend-dev:
    build:
      context: src/apps/ecommerce/frontend
      dockerfile: Dockerfile.dev
    environment:
      PORT: 5173
      VITE_BACKEND_URL: 'http://localhost:5172/v1'
    ports:
      - '5173:5173'
    volumes:
      - .:/app
    depends_on:
      backend-dev:
        condition: service_healthy
        restart: true
