services:
  db-dev:
    container_name: codexts-db-dev
    image: mongo:4.4
    environment:
      MONGO_INITDB_ROOT_USERNAME: codexts
      MONGO_INITDB_ROOT_PASSWORD: codexts
    command: mongod --quiet --logpath /dev/null
    ports:
      - '27017:27017'
    volumes:
      - codexts-db-dev:/data/db
    restart: on-failure

  backend-dev:
    container_name: codexts-backend-dev
    build:
      context: src/apps/ecommerce/backend
      dockerfile: Dockerfile.dev
    environment:
      NODE_ENV: development
      PORT: 3000
      DB_URI: 'mongodb://codexts:codexts@db-dev:27017/codexts-dev?authSource=admin'
      JWT_PRIVATE_KEY: codexts
    ports:
      - '3000:3000'
    volumes:
      - .:/app
    healthcheck:
      test: wget --no-verbose --tries=1 --spider backend-dev:3000
      interval: 3s
      timeout: 3s
      retries: 30
      start_period: 0s
    restart: on-failure

  frontend-dev:
    container_name: codexts-frontend-dev
    build:
      context: src/apps/ecommerce/frontend
      dockerfile: Dockerfile.dev
    environment:
      PORT: 3030
      VITE_BACKEND_URL: 'http://localhost:3000/v1'
    ports:
      - '3030:3030'
    volumes:
      - .:/app
    depends_on:
      backend-dev:
        condition: service_healthy
    restart: on-failure

volumes:
  codexts-db-dev:
