services:
  db:
    container_name: codexts-db
    image: mongo:4.4
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
    command: mongod --quiet --logpath /dev/null
    ports:
      - '27017:27017'
    volumes:
      - codexts-db:/data/db
    restart: always

  backend:
    container_name: codexts-backend
    build:
      context: .
      dockerfile: src/apps/ecommerce/backend/Dockerfile
      target: production
    env_file:
      - .env
    environment:
      PORT: 3000
      DB_URI: 'mongodb://${DB_USERNAME}:${DB_PASSWORD}@db:27017/${DB_NAME}?authSource=admin'
    ports:
      - '3000:3000'
    healthcheck:
      test: wget --no-verbose --tries=1 --spider backend:3000
      interval: 3s
      timeout: 3s
      retries: 30
      start_period: 0s
    restart: always

  frontend:
    container_name: codexts-frontend
    build:
      context: src/apps/ecommerce/frontend
      dockerfile: Dockerfile
      target: production
      args:
        BACKEND_URL: 'http://localhost:3000/v1'
    environment:
      PORT: 3030
    ports:
      - '3030:3030'
    depends_on:
      backend:
        condition: service_healthy
    restart: always

volumes:
  codexts-db:
