name: CI

on:
  push:
    branches: [main, ci/**]
  pull_request:
    branches: [main]

jobs:
  TruffleHog:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: TruffleHog OSS
        uses: trufflesecurity/trufflehog@main
        with:
          path: ./
          base: ${{ github.event.repository.default_branch }}
          head: HEAD
          extra_args: --debug --only-verified
  Lint:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: ./.github/actions/setup-node
      - name: Check
        run: npm run lint:check
  Tests:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 15
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    defaults:
      run:
        working-directory: ./tests
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: ./.github/actions/setup-node
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Unit
        run: npm run test:unit
      - name: Integration
        run: npm run test:integration
      - name: Acceptance
        run: npm run test:acceptance
      - name: Upload Reports
        uses: actions/upload-artifact@v3
        if: success() || failure()
        with:
          name: Tests Reports (${{ matrix.os }})
          path: ./tests/reports
          retention-days: 30
