name: CI

on:
  push:
    branches: [main, ci/**]
  pull_request:
    branches: [main]

jobs:
  TruffleHog:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: TruffleHog OSS
        uses: trufflesecurity/trufflehog@main
        with:
          path: ./
          base: ${{ github.event.repository.default_branch }}
          head: HEAD
          extra_args: --debug --only-verified

  Lint:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: ./.github/actions/setup-node

      - name: Check
        run: npm run lint:check

  Tests:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: ./.github/actions/setup-node

      - name: Unit, Integration & Acceptance
        run: npm run docker:test

      - name: Upload Reports
        uses: actions/upload-artifact@v3
        if: success() || failure()
        with:
          name: Tests Reports
          path: ./tests/reports
          retention-days: 30
